# Generated by Django 2.2.3 on 2019-08-12 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auth_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth_user',
            new_name='image_user',
        ),
    ]
