# Generated by Django 2.2.3 on 2019-08-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190821_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_detail',
            name='image',
            field=models.ImageField(default=1, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
