# Generated by Django 2.2.3 on 2019-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_school_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_detail',
            name='school_address',
            field=models.CharField(default='xyz', max_length=150),
            preserve_default=False,
        ),
    ]
