# Generated by Django 2.2.3 on 2019-09-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('person', models.IntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calc.Professor')),
            ],
        ),
    ]
