# Generated by Django 2.2.3 on 2019-09-07 07:41

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='job_title',
            field=models.CharField(default='aya', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calc.Class'),
        ),
    ]
