# Generated by Django 2.2.3 on 2019-09-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_others_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='year',
        ),
        migrations.AddField(
            model_name='salary',
            name='other',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='calc.Others'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_date',
            field=models.DateField(default='2019-08-06'),
            preserve_default=False,
        ),
    ]
