# Generated by Django 2.2.3 on 2019-09-08 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20190907_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calc.Others'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calc.Professor'),
        ),
    ]
