# Generated by Django 2.2.3 on 2019-09-08 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20190908_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]

