# Generated by Django 2.2.3 on 2019-09-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_salary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='name',
            field=models.CharField(default='ubaid', max_length=50),
            preserve_default=False,
        ),
    ]
